apiVersion: apps/v1
kind: Deployment
metadata:
  name: sp4-app-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sp4-app-test
  template:
    metadata:
      labels:
        app: sp4-app-test
    spec:
      imagePullSecrets:
        - name: harbor-eks-cred 
      containers:
      - name: sp4-app-test
        image: imagerepo.vaw.ai/backstage/sp4-app:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"  # Change application port
